### ISSUE TITLE
cannot import name 'MetaFrame' from 'metasynth'

### ISSUE THREAD

**Issue by Mrin7** [sodascience/metasynth#128]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[248], line 3
      1 import datetime as dt
      2 import polars as pl
----> 3 from metasynth import MetaFrame, demo_file

ImportError: cannot import name 'MetaFrame' from 'metasynth' (C:\Users\fnu178555\AppData\Local\anaconda3\lib\site-packages\metasynth\__init__.py)

**Comment by qubixes** [comment]
Hi @Mrin7, thanks for the issue. Which version of MetaSynth are you running? The examples are not compatible with the current version on PyPi. 

I will make a new release soon. If you want to try the current version on git (that uses the new `MetaFrame` class) you can do:

```sh
pip install git+https://github.com/sodascience/metasynth.git
```

@vankesteren I think we can make a new release now, or is there something you want to do before I make a new release?

**Comment by Mrin7** [comment]
@qubixes - Thanks for the link.
Also, can you share/link document on what's being used at the backend to generate data - GANs, Faker etc? How does it translate metadata to synthetic data? I would require this explanation, so that I can present my org with details.

**Comment by qubixes** [comment]
@Mrin7 Yes, of course. I looked a little bit in our documentation, and indeed I see that information is currently missing in our documentation. I'll make an issue to put a bit more detail of the backend/inner workings of MetaSynth.

We currently don't use any Neural Network/GAN based algorithms. We are currently starting a project to use some transformer type based algorithm for generating/inferring unstructured text, but that is still in the concept phase. When we are ready with that, we will probably offer it as an extension to keep dependencies low.

The backend used depends on the distribution fitted:

- `UniqueKeyDistribution` (1, 2, .. N): simple custom implementation
- Other discrete/continuous (int/float) distributions: use scipy
- time/date/datetime/categorical: simple custom implementation
- FakerDistribution: use Python Faker package
- RegexDistribution (structured text): pretty complicated custom implementation (uses sklearn CountVectorizer), currently being reworked (big improvement).

The metadata that is fitted contains information on the  statistics in (more or less) human  readable form. So for example if the distribution is a normal distribution it will have the parameters mu/sigma. From these it is relatively easy with scipy to generate synthetic data with the same distribution.

Summarizing, the back-ends are relatively simple/unsophisticated, and they are so by design so that the metadata can be understood by a human.

Does that give you enough information?

**Comment by Mrin7** [comment]
@qubixes Also, 
Can you please provide documentation for providers? I couldn't find anything on how to generate ssn, credit card info etc? 
The codes that I found online, are deprecated.
