### ISSUE TITLE
Error installing Library | git+https://github.com/sodascience/metasynth.git

### ISSUE THREAD

**Issue by Mrin7** [sodascience/metasynth#141]
Hi  , 
I tried to reinstall using the link , I am getting the following error.
"
Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
sys:1: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x21872940400>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x21872941c00>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
"

**Comment by vankesteren** [comment]
This seems like a general python install issue, or something with how you are running python. 

It will require some debugging from your side! Some questions to get you started:

- can you install other packages using the same installation method? e.g., `git+https://github.com/J535D165/scitree.git`
- is there something strange about your environment? Conda? WSL?

Closing, because likely unrelated to metasynth.
